/**
 * Local cache loader — reads pre-generated cache JSON files at build time.
 *
 * Cache files are stored at {monorepoRoot}/cache/{tenantId}/{table}.json
 * and follow the envelope format: { table, updatedAt, count, items[] }
 *
 * These files are generated by:
 * - scripts/seed-tenant.ts (initial seed)
 * - The API setItem endpoint (auto-updates cache on write)
 * - Manual export from Firestore
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

interface CacheEnvelope<T = unknown> {
  table: string
  updatedAt: string
  count: number
  items: T[]
}

const TENANT_ID = process.env.EXPORT_TENANT_ID ?? 'demo'

/**
 * Resolves the cache directory from the monorepo root.
 * process.cwd() in Next.js points to the app dir (src/apps/bonar-creator-studio).
 */
function cacheDir(): string {
  return resolve(process.cwd(), '..', '..', '..', 'cache', TENANT_ID)
}

/**
 * Loads a cached table from the local filesystem.
 * Returns the items array, or empty array if the file doesn't exist.
 */
export function loadCachedTable<T = unknown>(tableSlug: string): T[] {
  const filePath = resolve(cacheDir(), `${tableSlug}.json`)
  try {
    const raw = readFileSync(filePath, 'utf-8')
    const envelope = JSON.parse(raw) as CacheEnvelope<T>
    return envelope.items ?? []
  } catch {
    console.warn(`[load-cache] Cache file not found: ${filePath}`)
    return []
  }
}

/**
 * Loads the full cache envelope (includes metadata like updatedAt).
 */
export function loadCacheEnvelope<T = unknown>(tableSlug: string): CacheEnvelope<T> | null {
  const filePath = resolve(cacheDir(), `${tableSlug}.json`)
  try {
    const raw = readFileSync(filePath, 'utf-8')
    return JSON.parse(raw) as CacheEnvelope<T>
  } catch {
    return null
  }
}
