"""CLI subprocess smoke tests for serve-a2a-kit (Story K1A.5, AC2 + AC5).

Where ``test_a2a_integration.py`` exercises the A2A wiring in-process over an
ASGI transport, this module proves the *deployed* path: a real ``beddel serve``
child process, a real TCP socket, a real ``a2a.client`` talking JSON-RPC over
HTTP, and a real SIGTERM shutdown.

    subprocess: beddel serve --host 127.0.0.1 --port <ephemeral>
        -> GET  /health                          (readiness poll)
        -> GET  /.well-known/agent-card.json     (via a2a.client.create_client)
        -> POST /a2a                             (SendMessage, JSON-RPC)
        -> SIGTERM                               (clean shutdown)

Hermetic environment
--------------------
``beddel serve`` only mounts A2A when ``serve-a2a-kit`` is *enabled in the
SQLite kit index* (see the ``_a2a_kit_available`` gate in
``beddel.cli.commands._build_runtime_app``).  Both the index
(``~/.config/beddel/index.db``) and the global config
(``~/.config/beddel/config.json``) are resolved through ``Path.expanduser()``,
so this module points ``HOME`` at a throw-away directory and writes its own
config.  Consequences:

* A fresh index is created and ``IndexStore.sync_kits()`` inserts every
  discovered kit with ``enabled=1`` — so A2A mounts deterministically instead of
  depending on whatever the developer happens to have enabled locally.
* ``flows_paths`` points at a temp directory holding one generated workflow, so
  the Agent Card skill set is known exactly and no developer workflow (which may
  require an LLM provider, API keys or network) is ever executed.
* ``A2A_AUTH_TOKEN`` / ``A2A_PUBLIC_URL`` are stripped from the child env, so
  the loopback-no-auth path is what gets exercised (matching the default the
  Agent Card advertises: ``http://127.0.0.1:{port}``).

Deviation from AC2's literal wording
------------------------------------
AC2 is worded "assert no 'SDK not available' warning".  That string does not
exist anywhere in the current code — the K1A.3 rewrite replaced it.  Asserting
its absence would be a vacuous, always-passing assertion, so
``test_serve_subprocess_startup_reports_no_a2a_failure_diagnostics`` asserts on
the strings the current code actually emits when A2A fails to come up
(``_A2A_FAILURE_MARKERS``) *and* positively asserts the success line
``"A2A: /.well-known/agent-card.json (N workflow(s))"`` is present.

Known limitation surfaced by these tests
----------------------------------------
The task returned over JSON-RPC currently reaches ``TASK_STATE_FAILED`` with
"Workflow stream ended without a terminal event".  Root cause is in the SDK, not
in this kit: ``_build_runtime_app`` builds the A2A executor with
``DefaultDependencies(...)`` that has no ``lifecycle_hooks``, so
``WorkflowExecutor.__init__`` falls back to a no-op ``IHookManager()`` and
``execute_stream()`` yields *zero* events.  Fixing that is production work and
out of scope for a tests-only task, so the send test asserts what genuinely
proves AC2 — card discovery, dispatch, registry resolution and a terminal task
snapshot over the wire — and explicitly asserts the failure is *not* an
A2A-layer dispatch error, which is the part that would regress.
"""

from __future__ import annotations

import asyncio
import json
import os
import signal
import socket
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path
from typing import Any

import pytest

# ---------------------------------------------------------------------------
# Environment guards
# ---------------------------------------------------------------------------

pytest.importorskip("a2a", reason="a2a-sdk not installed")
pytest.importorskip("beddel.cli.commands", reason="beddel SDK not installed")

from a2a.types import TaskState  # noqa: E402 - must follow the importorskip guard above

_KITS_DIR = Path(__file__).resolve().parents[2]
"""``repo/kits`` — the directory ``kits_paths`` points at (parent of this kit)."""

if not (_KITS_DIR / "serve-a2a-kit" / "kit.yaml").is_file():
    pytest.skip(
        "serve-a2a-kit not found under the expected repo/kits/ layout; "
        "the subprocess smoke test cannot configure kits_paths",
        allow_module_level=True,
    )


pytestmark = pytest.mark.integration
"""Module-wide ``integration`` marker (Story K1A.5, AC7).

Declared *after* the ``importorskip`` / ``skip(allow_module_level=True)`` guards
above so a missing dependency still short-circuits collection cleanly.
"""


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_WORKFLOW_ID = "a2a_smoke_echo"
_WORKFLOW_NAME = "A2A Smoke Echo"

_WORKFLOW_YAML = f"""\
# Generated by test_a2a_smoke.py — deliberately provider-free.
# A single output-generator step renders a literal string, so executing this
# workflow needs no LLM provider, no API key and no network access.
id: {_WORKFLOW_ID}
name: {_WORKFLOW_NAME}
description: Renders a fixed string without calling any external provider.
version: "1.0"
steps:
  - id: echo
    primitive: output-generator
    config:
      format: text
      template: "a2a-smoke-ok"
"""

_READY_TIMEOUT_S = 90.0
"""Cold-start budget: kit discovery + index sync dominate, not uvicorn."""

_SHUTDOWN_TIMEOUT_S = 30.0
_RPC_TIMEOUT_S = 60.0

_A2A_SUCCESS_PREFIX = "A2A: /.well-known/agent-card.json"

_A2A_FAILURE_MARKERS = (
    # beddel.cli.commands._build_runtime_app -> except ImportError
    "beddel_serve_a2a is not importable",
    # ... -> except Exception
    "A2A kit setup failed",
    # ... -> fail-closed non-loopback guard
    "A2A_AUTH_TOKEN required for non-loopback A2A",
    # ... -> empty registry guard
    "Agent Card has zero skills",
    # generic Click failure envelope for any of the above
    "Error: serve-a2a-kit",
)

_LEAK_MARKERS = (
    "Task exception was never retrieved",
    "was never awaited",
    "Task was destroyed but it is pending",
    "ResourceWarning",
    "Unclosed client session",
    "Unclosed connector",
    "Traceback (most recent call last)",
)

_TERMINAL_STATE_NAMES = frozenset(
    {"TASK_STATE_COMPLETED", "TASK_STATE_FAILED", "TASK_STATE_CANCELED"}
)

_DISPATCH_ERROR_FRAGMENTS = (
    "not found in registry",
    "Missing 'workflow_id'",
)


# ---------------------------------------------------------------------------
# Subprocess harness
# ---------------------------------------------------------------------------


def _free_port() -> int:
    """Reserve then release an ephemeral port.

    There is an unavoidable race between releasing the socket and the child
    binding it; the window is small and the alternative (letting uvicorn pick)
    gives no way to build the client URL.
    """
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _serve_command(port: int) -> list[str]:
    """Return the ``beddel serve`` argv, preferring the installed console script.

    Falls back to ``python -c`` because ``python -m beddel.cli`` does not work:
    ``beddel.cli`` is a package with no ``__main__``.
    """
    console_script = Path(sys.executable).parent / "beddel"
    if console_script.is_file():
        return [
            str(console_script),
            "serve",
            "--host",
            "127.0.0.1",
            "--port",
            str(port),
        ]
    return [
        sys.executable,
        "-c",
        "from beddel.cli import main; main()",
        "serve",
        "--host",
        "127.0.0.1",
        "--port",
        str(port),
    ]


class _ServeProcess:
    """A ``beddel serve`` child process with drained stdout/stderr.

    Both pipes are drained by daemon reader threads.  That matters for two
    reasons: the child would otherwise block once a pipe buffer fills, and the
    tests need to inspect startup output *while the server is still running*.
    """

    def __init__(self, home: Path) -> None:
        self._home = home
        self.port = _free_port()
        self.base_url = f"http://127.0.0.1:{self.port}"
        self.stdout_lines: list[str] = []
        self.stderr_lines: list[str] = []
        self._proc: subprocess.Popen[str] | None = None
        self._readers: list[threading.Thread] = []

    # -- lifecycle ------------------------------------------------------

    def _child_env(self) -> dict[str, str]:
        stripped = {"HOME", "XDG_CONFIG_HOME", "A2A_AUTH_TOKEN", "A2A_PUBLIC_URL"}
        env = {k: v for k, v in os.environ.items() if k not in stripped}
        env["HOME"] = str(self._home)
        env["NO_COLOR"] = "1"
        env["PYTHONUNBUFFERED"] = "1"
        # Surface leaked coroutines/tasks as warnings we can assert on (AC5).
        env["PYTHONWARNINGS"] = "always::ResourceWarning"
        return env

    def start(self) -> None:
        self._proc = subprocess.Popen(  # noqa: S603 - argv is built locally, no shell
            _serve_command(self.port),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.DEVNULL,
            text=True,
            env=self._child_env(),
            # cwd is the throw-away HOME so no project-level .beddel.json in the
            # real workspace can override the config written for this test.
            cwd=str(self._home),
        )
        for stream, sink in (
            (self._proc.stdout, self.stdout_lines),
            (self._proc.stderr, self.stderr_lines),
        ):
            assert stream is not None  # PIPE was requested for both
            thread = threading.Thread(
                target=self._drain, args=(stream, sink), daemon=True
            )
            thread.start()
            self._readers.append(thread)

    @staticmethod
    def _drain(stream: Any, sink: list[str]) -> None:
        for line in stream:
            sink.append(line.rstrip("\n"))

    def wait_until_ready(self) -> None:
        """Poll the pre-existing ``/health`` route until the server answers."""
        assert self._proc is not None
        stop_at = time.monotonic() + _READY_TIMEOUT_S
        last_error = "timed out before any response"
        while time.monotonic() < stop_at:
            if self._proc.poll() is not None:
                pytest.fail(
                    f"beddel serve exited during startup (rc={self._proc.returncode}).\n"
                    f"{self.diagnostics()}"
                )
            try:
                with urllib.request.urlopen(  # noqa: S310 - fixed loopback http URL
                    f"{self.base_url}/health", timeout=2
                ) as response:
                    if response.status == 200:
                        payload = json.loads(response.read().decode())
                        assert payload["status"] == "ok", payload
                        return
                    last_error = f"HTTP {response.status}"
            except (urllib.error.URLError, OSError, TimeoutError) as exc:
                last_error = f"{type(exc).__name__}: {exc}"
            time.sleep(0.25)

        self.stop()
        pytest.fail(
            f"beddel serve never became ready within {_READY_TIMEOUT_S}s "
            f"(last error: {last_error}).\n{self.diagnostics()}"
        )

    def stop(self) -> int:
        """SIGTERM, then SIGKILL as a last resort. Idempotent."""
        if self._proc is None:
            return 0
        if self._proc.poll() is None:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=_SHUTDOWN_TIMEOUT_S)
            except subprocess.TimeoutExpired:
                self._proc.kill()
                self._proc.wait(timeout=_SHUTDOWN_TIMEOUT_S)
        for thread in self._readers:
            thread.join(timeout=5.0)
        return int(self._proc.returncode)

    # -- introspection --------------------------------------------------

    @property
    def stdout(self) -> str:
        return "\n".join(self.stdout_lines)

    @property
    def stderr(self) -> str:
        return "\n".join(self.stderr_lines)

    def diagnostics(self) -> str:
        return f"--- stdout ---\n{self.stdout}\n--- stderr ---\n{self.stderr}"


def _write_hermetic_home(root: Path) -> Path:
    """Create the throw-away ``HOME`` (config + flows) and return its path."""
    home = root / "home"
    flows_dir = root / "flows"
    config_dir = home / ".config" / "beddel"
    config_dir.mkdir(parents=True, exist_ok=True)
    flows_dir.mkdir(parents=True, exist_ok=True)
    (flows_dir / "a2a-smoke-echo.yaml").write_text(_WORKFLOW_YAML, encoding="utf-8")
    (config_dir / "config.json").write_text(
        json.dumps({"kits_paths": [str(_KITS_DIR)], "flows_paths": [str(flows_dir)]}),
        encoding="utf-8",
    )
    return home


def _spawn_server(root: Path) -> _ServeProcess:
    server = _ServeProcess(_write_hermetic_home(root))
    server.start()
    server.wait_until_ready()
    return server


# ---------------------------------------------------------------------------
# A2A client driver
# ---------------------------------------------------------------------------


def _resolve_card(base_url: str) -> Any:
    """Fetch and ProtoJSON-parse the Agent Card over real HTTP."""

    async def _run() -> Any:
        import httpx
        from a2a.client import A2ACardResolver

        async with httpx.AsyncClient(timeout=10.0) as http_client:
            resolver = A2ACardResolver(httpx_client=http_client, base_url=base_url)
            return await resolver.get_agent_card()

    return asyncio.run(asyncio.wait_for(_run(), timeout=_RPC_TIMEOUT_S))


def _send_message(base_url: str) -> tuple[str, list[Any]]:
    """Send one message over real HTTP JSON-RPC and collect the stream.

    Uses the public ``a2a.client.create_client`` entry point with a *URL*: it
    fetches ``/.well-known/agent-card.json`` itself and then talks to whatever
    endpoint the card advertises, so a mis-advertised URL fails here rather than
    passing silently.

    Returns ``(sent_message_id, stream_responses)`` so callers can assert the
    server echoed back the very message they sent.
    """
    message_id = str(uuid.uuid4())

    async def _run() -> list[Any]:
        from a2a.client import create_client
        from a2a.types import Message, Part, Role, SendMessageRequest
        from google.protobuf import json_format
        from google.protobuf.struct_pb2 import Value

        client = await create_client(agent=base_url)
        try:
            data_value = Value()
            json_format.ParseDict({"workflow_id": _WORKFLOW_ID}, data_value)
            request = SendMessageRequest(
                message=Message(
                    role=Role.ROLE_USER,
                    parts=[Part(data=data_value)],
                    message_id=message_id,
                ),
            )
            return [response async for response in client.send_message(request)]
        finally:
            await client.close()

    responses = asyncio.run(asyncio.wait_for(_run(), timeout=_RPC_TIMEOUT_S))
    return message_id, responses


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def a2a_server(tmp_path_factory: pytest.TempPathFactory) -> Any:
    """One ``beddel serve`` process shared by the read-only smoke tests.

    Module-scoped because cold start is dominated by kit discovery + index sync;
    the shutdown test deliberately runs its own process so it can assert on that
    process's full lifecycle.
    """
    root = tmp_path_factory.mktemp("a2a-smoke-serve")
    server = _spawn_server(root)
    try:
        yield server
    finally:
        server.stop()


# ---------------------------------------------------------------------------
# AC2: beddel serve exposes A2A over a real socket
# ---------------------------------------------------------------------------


def test_serve_subprocess_mounts_a2a_and_advertises_loopback_card(
    a2a_server: _ServeProcess,
) -> None:
    """``beddel serve`` mounts A2A and advertises a reachable loopback URL.

    Guards the ``_a2a_kit_available`` gate: had the kit not been discovered and
    enabled, the process would still serve ``/health`` happily while exposing no
    A2A routes at all, and this assertion is what catches that.
    """
    assert _A2A_SUCCESS_PREFIX in a2a_server.stdout, a2a_server.diagnostics()
    assert f"A2A RPC: POST {a2a_server.base_url}/a2a" in a2a_server.stdout, (
        a2a_server.diagnostics()
    )


def test_serve_subprocess_agent_card_exposes_only_the_generated_workflow(
    a2a_server: _ServeProcess,
) -> None:
    """The card resolved over HTTP lists exactly the workflow this test wrote.

    Doubles as proof that the hermetic ``HOME`` took effect — if the developer's
    real ``flows_paths`` had leaked in, extra skills would appear here.
    """
    card = _resolve_card(a2a_server.base_url)

    assert card.name == "Beddel Agent"
    assert {skill.id for skill in card.skills} == {_WORKFLOW_ID}
    assert card.capabilities.streaming is True
    advertised = {interface.url for interface in card.supported_interfaces}
    assert advertised == {f"{a2a_server.base_url}/a2a"}


def test_serve_subprocess_send_message_returns_terminal_task(
    a2a_server: _ServeProcess,
) -> None:
    """A real JSON-RPC SendMessage round-trips to a terminal task snapshot.

    Asserted, in order of what each step proves:

    1. the first response is a ``Task`` in ``SUBMITTED`` whose history echoes
       the exact ``message_id`` sent -> our message reached the executor;
    2. the last response carries a terminal state -> the task lifecycle ran to
       completion instead of hanging;
    3. no dispatch-layer failure ("workflow not found", "missing workflow_id")
       -> the Agent Card skill actually resolved in the server-side registry.

    See the module docstring: the terminal state is currently ``FAILED`` because
    the SDK wires the A2A executor without lifecycle hooks. That is a production
    defect, not a transport defect, so this test asserts the transport and
    dispatch guarantees that must hold either way rather than pinning the
    current-but-wrong terminal state.
    """
    sent_message_id, responses = _send_message(a2a_server.base_url)

    assert len(responses) >= 2, (
        f"expected at least a Task plus a terminal update: {responses}"
    )

    first = responses[0]
    assert first.HasField("task"), f"first stream response must be a Task: {first}"
    assert first.task.status.state == TaskState.TASK_STATE_SUBMITTED
    assert first.task.id, "server must assign a task id"
    assert sent_message_id in {message.message_id for message in first.task.history}, (
        "task history must echo the message that was sent"
    )

    last = responses[-1]
    terminal_state, terminal_text = _terminal_state_and_text(last)
    assert terminal_state in _TERMINAL_STATE_NAMES, (
        f"task never reached a terminal state (got {terminal_state}): {last}"
    )

    for fragment in _DISPATCH_ERROR_FRAGMENTS:
        assert fragment not in terminal_text, (
            f"A2A dispatch failed rather than the workflow itself: {terminal_text!r}"
        )

    # The request really crossed the socket, not an in-process shortcut.
    assert 'POST /a2a HTTP/1.1" 200' in a2a_server.stdout, a2a_server.diagnostics()


def test_serve_subprocess_startup_reports_no_a2a_failure_diagnostics(
    a2a_server: _ServeProcess,
) -> None:
    """No A2A bring-up failure appears in the captured startup logs.

    AC2 words this as "no 'SDK not available' warning"; that string no longer
    exists in ``beddel.cli.commands``, so asserting its absence would always
    pass. These markers are the ones the current code emits instead.
    """
    combined = f"{a2a_server.stdout}\n{a2a_server.stderr}"
    for marker in _A2A_FAILURE_MARKERS:
        assert marker not in combined, f"A2A bring-up reported {marker!r}:\n{combined}"

    # Positive counterpart: absence-only assertions cannot distinguish
    # "A2A came up cleanly" from "A2A never came up".
    assert _A2A_SUCCESS_PREFIX in a2a_server.stdout


# ---------------------------------------------------------------------------
# AC5: clean shutdown
# ---------------------------------------------------------------------------


def test_serve_subprocess_terminates_cleanly_after_serving_a2a_traffic(
    tmp_path: Path,
) -> None:
    """SIGTERM after a real A2A request shuts down without leak warnings.

    Runs its own server so the assertions cover one full lifecycle — start,
    serve an A2A task, terminate — rather than a process that only ever answered
    ``/health``. A leaked task store or unawaited executor coroutine would show
    up in the child's stderr on shutdown.
    """
    server = _spawn_server(tmp_path)
    terminated = False
    try:
        _, responses = _send_message(server.base_url)
        assert responses, "no A2A response before shutdown; nothing to leak"

        returncode = server.stop()
        terminated = True
    finally:
        if not terminated:
            server.stop()

    # SIGTERM-on-uvicorn is a normal exit; 0 and -SIGTERM are both clean.
    assert returncode in (0, -signal.SIGTERM), (
        f"unclean exit rc={returncode}\n{server.diagnostics()}"
    )

    combined = f"{server.stdout}\n{server.stderr}"
    assert "Application shutdown complete" in combined, server.diagnostics()
    assert "Finished server process" in combined, server.diagnostics()

    for marker in _LEAK_MARKERS:
        assert marker not in combined, f"shutdown reported {marker!r}:\n{combined}"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _terminal_state_and_text(response: Any) -> tuple[str, str]:
    """Extract ``(state_name, agent_message_text)`` from a final StreamResponse.

    a2a-sdk 1.1.2 ends a *streaming* send with a ``TaskStatusUpdateEvent`` and a
    *non-streaming* send with a ``Task`` snapshot, so both shapes are handled.
    """
    if response.HasField("status_update"):
        status = response.status_update.status
    elif response.HasField("task"):
        status = response.task.status
    else:  # pragma: no cover - defensive: neither shape carries a status
        return "<no-status>", ""

    text = " ".join(part.text for part in status.message.parts if part.HasField("text"))
    return str(TaskState.Name(status.state)), text
